//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IdCliente { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> DomicilioId { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
