//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosBancarios
    {
        public DatosBancarios()
        {
            this.Restaurante = new HashSet<Restaurante>();
        }
    
        public int Id { get; set; }
        public string NumeroCuenta { get; set; }
        public string CBU { get; set; }
    
        public virtual ICollection<Restaurante> Restaurante { get; set; }
    }
}
