//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public Domicilio()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Restaurante = new HashSet<Restaurante>();
        }
    
        public int Id { get; set; }
        public string NombreCalle { get; set; }
        public string NumeroCalle { get; set; }
        public Nullable<int> NumeroPiso { get; set; }
        public string NumeroDpto { get; set; }
        public int LocalidadId { get; set; }
        public System.Data.Spatial.DbGeography Ubicacion { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Restaurante> Restaurante { get; set; }
    }
}
