//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public Domicilio()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Restaurante = new HashSet<Restaurante>();
        }
    
        public int Id { get; set; }
        public string NombreCalle { get; set; }
        public int NumeroCalle { get; set; }
        public int NumeroPiso { get; set; }
        public int NumeroDpto { get; set; }
        public int LocalidadId { get; set; }
        public System.Data.Spatial.DbGeography Ubicacion { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<Restaurante> Restaurante { get; set; }
    }
}
