//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public Localidad()
        {
            this.Domicilio = new HashSet<Domicilio>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int PartidoId { get; set; }
    
        public virtual ICollection<Domicilio> Domicilio { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
