//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Plato = new HashSet<Plato>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> EstiloMenuId { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual EstiloMenu EstiloMenu { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual ICollection<Plato> Plato { get; set; }
    }
}
