//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Plato = new HashSet<Plato>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RestauranteId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> EstiloMenuId { get; set; }
        public Nullable<int> PlatoId { get; set; }
    
        public virtual EstiloMenu EstiloMenu { get; set; }
        public virtual Restaurante Restaurante { get; set; }
        public virtual ICollection<Plato> Plato { get; set; }
    }
}
