//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbReservantesEntities : DbContext
    {
        public dbReservantesEntities()
            : base("name=dbReservantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<DatosBancarios> DatosBancarios { get; set; }
        public DbSet<Domicilio> Domicilio { get; set; }
        public DbSet<EstadoReserva> EstadoReserva { get; set; }
        public DbSet<EstiloMenu> EstiloMenu { get; set; }
        public DbSet<Localidad> Localidad { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Partido> Partido { get; set; }
        public DbSet<Plato> Plato { get; set; }
        public DbSet<PlatosElegidos> PlatosElegidos { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<Restaurante> Restaurante { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoUsuario> TipoUsuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
