//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelRestaurante
    {
        public NivelRestaurante()
        {
            this.Restaurante = new HashSet<Restaurante>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Descripcion { get; set; }
        public int EnumValue { get; set; }
    
        public virtual ICollection<Restaurante> Restaurante { get; set; }
    }
}
