//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        public Partido()
        {
            this.Localidad = new HashSet<Localidad>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
    
        public virtual ICollection<Localidad> Localidad { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
