//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        public Partido()
        {
            this.Localidad = new HashSet<Localidad>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
    
        public virtual ICollection<Localidad> Localidad { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
