//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatosElegidos
    {
        public int ReservaId { get; set; }
        public int PlatoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Plato Plato { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
