//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatosElegidos
    {
        public int ReservaId { get; set; }
        public int PlatoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Plato Plato { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
