//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        public Plato()
        {
            this.PlatosElegidos = new HashSet<PlatosElegidos>();
        }
    
        public int Id { get; set; }
        public string NombrePlato { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
        public virtual ICollection<PlatosElegidos> PlatosElegidos { get; set; }
    }
}
