//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        public Plato()
        {
            this.PlatosElegidos = new HashSet<PlatosElegidos>();
        }
    
        public int Id { get; set; }
        public string NombrePlato { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }
        public int RestauranteId { get; set; }
    
        public virtual Restaurante Restaurante { get; set; }
        public virtual ICollection<PlatosElegidos> PlatosElegidos { get; set; }
    }
}
