//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> RestaurenteId { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> EstadoReservaId { get; set; }
    
        public virtual EstadoReserva EstadoReserva { get; set; }
        public virtual Restaurante Restaurante { get; set; }
    }
}
