//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        public Restaurante()
        {
            this.DatosBancarios = new HashSet<DatosBancarios>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> DatosBancariosId { get; set; }
        public Nullable<int> CUIT { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual ICollection<DatosBancarios> DatosBancarios { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
