//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservAntes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        public Restaurante()
        {
            this.Plato = new HashSet<Plato>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IdRestaurante { get; set; }
        public int IdUsuario { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> DatosBancariosId { get; set; }
        public Nullable<int> DomicilioId { get; set; }
        public string CUIT { get; set; }
        public Nullable<int> CantidadClientes { get; set; }
        public bool Habilitado { get; set; }
        public string Foto { get; set; }
        public Nullable<int> NivelId { get; set; }
    
        public virtual DatosBancarios DatosBancarios { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        public virtual NivelRestaurante NivelRestaurante { get; set; }
        public virtual ICollection<Plato> Plato { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
